sudo: required

services:
 - docker

before_install:
  - docker build -t carlosfib/client-test -f ./client/Dockerfile.dev ./client


script:
 - docker run -e CI=true carlosfib/client-test npm test

after_success:
 - docker build -t 19920508/client ./client
 - docker build -t 19920508/nginx ./nginx
 - docker build -t 19920508/server ./server
 - docker build -t 19920508/worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push 19920508/client
 - docker push 19920508/nginx
 - docker push 19920508/server
 - docker push 19920508/worker